export const CATEGORY_SELECTED = "CATEGORY_SELECTED";
export const LOCATION_SELECTED = "LOCATION_SELECTED";
export const VEHICLE_SELECTED = "VEHICLE_SELECTED";
export const DATE_SELECTED = "DATE_SELECTED";
export const SET_STEP = "SET_STEP";
